Start = input("Would you like to create a Mad Lib story? yes/no: ")
while Start == "yes":
    Topic = input("What kind of topic would you like? Simon Story/2/3/4: ")
    if Topic == "Simon Story":
        Input1 = input("Type a living thing: ")
        Input2 = input("Type a male name: ")
        Input3 = input("Type a name of a place: ")
        Input4 = input("Type a female name: ")
        Input5 = input("Type a ethnicity: ")
        Input6 = input("Type a body part: ")
        Input7 = input("Type a action: ")
        Input8 = input("Type a class subject: ")
        Input9 = input("Type a body part: ")
        Input10 = input("Type a: ")
        Input11 = input("Type a: ")
        Input12 = input("Type a: ")
        Input13 = input("Type a: ")
        Input14 = input("Type a: ")
        Input15 = input("Type a: ")
        print("Mad Libs Testing Format: " + Input1 + Input2 + Input3)
    if Topic == "2":
        Input1 = input("Type a: ")
        Input2 = input("Type a: ")
        Input3 = input("Type a: ")
        Input4 = input("Type a: ")
        Input5 = input("Type a: ")
        Input6 = input("Type a: ")
        Input7 = input("Type a: ")
        Input8 = input("Type a: ")
        Input9 = input("Type a: ")
        Input10 = input("Type a: ")
        Input11 = input("Type a: ")
        Input12 = input("Type a: ")
        Input13 = input("Type a: ")
        Input14 = input("Type a: ")
        Input15 = input("Type a: ")
        print("Mad Libs Testing Format: " + Input1 + Input2 + Input3)
    if Topic == "3":
        Input1 = input("Type a: ")
        Input2 = input("Type a: ")
        Input3 = input("Type a: ")
        Input4 = input("Type a: ")
        Input5 = input("Type a: ")
        Input6 = input("Type a: ")
        Input7 = input("Type a: ")
        Input8 = input("Type a: ")
        Input9 = input("Type a: ")
        Input10 = input("Type a: ")
        Input11 = input("Type a: ")
        Input12 = input("Type a: ")
        Input13 = input("Type a: ")
        Input14 = input("Type a: ")
        Input15 = input("Type a: ")
        print("Mad Libs Testing Format: " + Input1 + Input2 + Input3)
    if Topic == "4":
        Input1 = input("Type a: ")
        Input2 = input("Type a: ")
        Input3 = input("Type a: ")
        Input4 = input("Type a: ")
        Input5 = input("Type a: ")
        Input6 = input("Type a: ")
        Input7 = input("Type a: ")
        Input8 = input("Type a: ")
        Input9 = input("Type a: ")
        Input10 = input("Type a: ")
        Input11 = input("Type a: ")
        Input12 = input("Type a: ")
        Input13 = input("Type a: ")
        Input14 = input("Type a: ")
        Input15 = input("Type a: ")
        print("Mad Libs Testing Format: " + Input1 + Input2 + Input3)
    
    print("Why end now?! ")
while Start != "yes":
    print("You could have had so much fun, but you choose not to. Bye Bye, but I mean if you choose to leave it's obvious you do not value Util and therefore you will loose your next ballot. And judge, this is why you should vote for the affirmative. ")
    break